<?php
require 'vendor/phpmailer/phpmailer/src/PHPMailer.php';
require 'vendor/phpmailer/phpmailer/src/SMTP.php';
require 'vendor/phpmailer/phpmailer/src/Exception.php';

use PHPMailer\PHPMailer\PHPMailer;

$mail = new PHPMailer(true); //defaults to using php "mail()"; the true param means it will throw exceptions on errors, which we need to catch
$mail->isSMTP();
$mail->Host = 'smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Username = 'abhishekps6282@gmail.com'; //paste one generated by Mailtrap
$mail->Password = 'gwwvbxyniklesrdx'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 587;
try {
    $mail->AddAddress('abhishekps6282@gmail.com', 'Titan');
    $mail->SetFrom($_POST['email'], 'Titan Website');

    $mail->Subject = 'Titan website - Request for a Product';
    $mail->AltBody = 'To view the message, please use an HTML compatible email viewer!'; // optional - MsgHTML will create an alternate automatically

    $mailContent = "<h2>Dear Team <br> We have an enquiry  </h2>
    <p>Name :" . $_POST['name'] . " </p>";
    $mailContent = $mailContent . "<p>BIM file :" . $_POST['BimList'] . " </p>";
    $mailContent = $mailContent . "<p>Email :" . $_POST['email'] . " </p>";
    $mailContent = $mailContent . "<p>Phone :" . $_POST['phone'] . " </p>";
    $mailContent = $mailContent . "<p>enquery :" . $_POST['enquery'] . " </p>";
    $mailContent = $mailContent . "<p>profession :" . $_POST['profession'] . " </p>";
    $mailContent = $mailContent . "<p>Thanks,<p>";
    $mailContent = $mailContent . "<p>Admin<p>";

    $mail->Body = $mailContent;
    $mail->Send();
    echo "Message Sent OK\n";
// } catch (phpmailerException $e) {
//     echo $e->errorMessage(); //Pretty error messages from PHPMailer
} catch (Exception $e) {
    echo $e->getMessage(); //Boring error messages from anything else!
}


// echo "Email Sent : \n";
// echo "Thankyou for contacting us, we will get back you soon \n";
exit;
