<?php
require 'vendor/phpmailer/phpmailer/src/PHPMailer.php';
require 'vendor/phpmailer/phpmailer/src/SMTP.php';
require 'vendor/phpmailer/phpmailer/src/Exception.php';

use PHPMailer\PHPMailer\PHPMailer;

$name = '';
$email = '';
$phone = '';
$enquiry = '';
$profession = '';
$intrested = '';
$success = false;

if (($_SERVER['REQUEST_METHOD'] == 'POST')) {
    $data = $_POST;
    $name = $data['name'];
    $email = $data['email'];
    $phone = $data['phone'];
    $enquiry = $data['enquiry'];
    $profession = $data['profession'];
    $intrested = $data['intrested'];

    if (('' !== $name) && ('' !== $email) && ('' !== $phone)) {
        $mail = new PHPMailer(true); //defaults to using php "mail()"; the true param means it will throw exceptions on errors, which we need to catch
        $mail->isSMTP();
        $mail->Host = 'smtp.gmail.com';
        $mail->SMTPAuth = true;
        $mail->Username = 'titanuaegt@gmail.com'; //paste one generated by Mailtrap
        $mail->Password = 'nejjpteggjeidumo'; //paste one generated by Mailtrap
        $mail->SMTPSecure = 'tls';
        $mail->Port = 587;
        try {
            $mail->AddAddress('philip@titanindustries.me', 'Titan');

            $mail->SetFrom($email, $name);

            $mail->Subject = 'Titan website - Contact form';
            $mail->AltBody = 'To view the message, please use an HTML compatible email viewer!'; // optional - MsgHTML will create an alternate automatically

            $mailContent = "<h2>Dear Team <br> We have an enquiry  </h2>
    <p>Name :" . $_POST['name'] . " </p>";
            $mailContent = $mailContent . "<p>Email :" . $_POST['email'] . " </p>";
            $mailContent = $mailContent . "<p>Phone :" . $_POST['phone'] . " </p>";
            $mailContent = $mailContent . "<p>enquiry :" . $_POST['enquiry'] . " </p>";
            $mailContent = $mailContent . "<p>profession :" . $_POST['profession'] . " </p>";
            $mailContent = $mailContent . "<p>intrested :" . $_POST['intrested'] . " </p>";
            $mailContent = $mailContent . "<p>Thanks,<p>";
            $mailContent = $mailContent . "<p>Admin<p>";

            $mail->Body = $mailContent;
            if ($mail->Send()) {
                //echo "Message Sent OK\n";
                $success = true;
            }
            // } catch (phpmailerException $e) {
            //     echo $e->errorMessage(); //Pretty error messages from PHPMailer
        } catch (Exception $e) {
            echo $e->getMessage(); //Boring error messages from anything else!
        }
    }
} 


// echo "Email Sent : \n";
// echo "Thankyou for contacting us, we will get back you soon \n";
// echo json_encode(['success' => $success]);
echo $success;

exit;
